### ISSUE TITLE
sendTransaction socket.timeout

### ISSUE THREAD

**Issue by JonathanVandal** [pipermerriam/web3.py#125]
* Version: latest
* Python: 2.7
* OS: linux

### What was wrong?
I'm trying to send a transaction from an account to `Ropsten` another but I got error `socket timeout`

```
Traceback (most recent call last):
  File "rpc-client.py", line 11, in <module>
    print web3rpc.eth.sendTransaction({'to': john, 'from': web3rpc.eth.coinbase, 'value': 12345})
  File "/usr/local/lib/python2.7/dist-packages/web3/eth.py", line 243, in sendTransaction
    [formatters.input_transaction_formatter(self, formatted_transaction)],
  File "/usr/local/lib/python2.7/dist-packages/web3/providers/manager.py", line 37, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/usr/local/lib/python2.7/dist-packages/web3/providers/rpc.py", line 161, in make_request
    response = self.client.post(self.path, body=request_data)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 218, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/client.py", line 200, in request
    block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/usr/local/lib/python2.7/dist-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/usr/local/lib/python2.7/dist-packages/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
socket.timeout: timed out 
```

Here is my python script (I'm connected to my server, assuming my remove server IP is : 128.49.52.154) :  

```
from web3 import Web3, KeepAliveRPCProvider

web3rpc = Web3(KeepAliveRPCProvider())
web3rpc = Web3(KeepAliveRPCProvider(host="128.49.52.154", port="8545"))

john = '0xe7bcd3b454c18313fe88d679eaf41251a58793dd'

print web3rpc.eth.sendTransaction({'to': john, 'from': web3rpc.eth.coinbase, 'value': 12345})
```
I thought it was because I'm using the `Ropsten testnet` and I have to use `TestRPCProvider `  instead of `KeepAliveRPCProvider`.

But when I'm using `TestRPCProvider` I have this error : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 347, in serve_forever
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/gevent/baseserver.py", line 291, in start
    self.init_socket()
  File "/usr/local/lib/python2.7/dist-packages/gevent/pywsgi.py", line 1222, in init_socket
    StreamServer.init_socket(self)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 80, in init_socket
    self.socket = self.get_listener(self.address, self.backlog, self.family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 91, in get_listener
    return _tcp_listener(address, backlog=backlog, reuse_addr=self.reuse_addr, family=family)
  File "/usr/local/lib/python2.7/dist-packages/gevent/server.py", line 177, in _tcp_listener
    sock.bind(address)
  File "<string>", line 1, in bind
TypeError: an integer is required
<Greenlet at 0x7f43a554d550: <bound method WSGIServer.serve_forever of <WSGIServer at 0x7f43a5526a50 address=128.49.52.154>>> failed with TypeError

Exception AttributeError: "'NoneType' object has no attribute 'rmtree'" in <bound method state.__del__ of <ethereum.tester.state object at 0x7f43a5543650>> ignored
```

With this code : 

```
from web3 import Web3, TestRPCProvider

web3rpc = Web3(TestRPCProvider())
web3rpc = Web3(TestRPCProvider(host="128.49.52.154", port="8545"))

print web3rpc.eth.coinbase
```

Anyone know how can I fix my `socket error` or `TestRPCProvider` error ? Or Maybe the socket timeout error is caused by the connection to my remote server ? The connection must be in localhost ?

#### Cute Animal Picture

![Cute animal picture](https://s-media-cache-ak0.pinimg.com/736x/58/c9/e8/58c9e86c04cb775daeab4b9fa69178a3.jpg)

**Comment by JonathanVandal** [comment]
I fixed my problem with unlock my account : 

```
web3rpc.personal.unlockAccount(web3rpc.eth.coinbase, 'your-passphrase')
```
