### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by insoftayyappans** [pipermerriam/web3.py#146]
* Version: Latest
* Python: 2.7
* OS: Linux/Ubuntu 14.04 LTS

### What was wrong?
I am trying to create an account and list out the accounts. But i got "socket.timeout: timed out"

**My Log is:**

> Traceback (most recent call last):
  File "/home/insipc208/Desktop/Eth/Example/create_account.py", line 10, in <module>
    web3rpc.personal.newAccount('insoftindia')
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/web3/utils/string.py", line 83, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/web3/personal.py", line 49, in newAccount
    "personal_newAccount", [password],
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/web3/providers/manager.py", line 41, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/web3/providers/rpc.py", line 160, in make_request
    response = self.client.post(self.path, body=request_data)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 218, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/geventhttpclient/client.py", line 200, in request
    block_size=self.block_size, method=method.upper(), headers_type=self.headers_type)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/geventhttpclient/response.py", line 190, in _read_headers
    data = self._sock.recv(self.block_size)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
socket.timeout: timed out

**My Code:**

```
from web3 import Web3, KeepAliveRPCProvider, IPCProvider

web3rpc = Web3(KeepAliveRPCProvider(host='localhost', port='8545'))

print dir(web3rpc.personal.web3.eth)

web3rpc.personal.newAccount('insoftindia')

print web3rpc.eth.accounts
```

**Using testnet:**

> pyethapp --profile morden --data-dir '/home/insipc208/Desktop/Eth/pyethapp_data/state' -c jsonrpc.listen_port=8545 run

Could please suggest to solve this? 

#### Cute Animal Picture

![Cute animal picture]()

**Comment by pipermerriam** [comment]
This looks like a legitimate timeout.  PyEthapp has historically been very slow when creating new accounts.  Can you try the following?

```
web3rpc = Web3(KeepAliveRPCProvider(host='localhost', port='8545', network_timeout=600, connection_timeout=600))
```

That code may hang for up to 10 minutes waiting for pyethapp to generate the account.  Feel free to adjust that number to your desired limit.  Let me know if this doesn't fix your issue.

**Comment by insoftayyappans** [comment]
As you said, i have increased time out attribute. But still getting same timeout error. In pyethapp, shows following error:

> INFO:accounts	adding account account=<Account(address=1f092211f27a117c025fb3bc2fedaf38a2d664ad, id=None)>
> Traceback (most recent call last):
>   File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/gevent/greenlet.py", line 534, in run
>     result = self._run(*self.args, **self.kwargs)
>   File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/tinyrpc/server/__init__.py", line 51, in handle_message
>     response = self.dispatcher.dispatch(request)
>   File "/opt/ethereum/pyethapp/.venv/local/lib/python2.7/site-packages/pyethapp/jsonrpc.py", line 121, in dispatch
>     self.logger('RPC error', id=res.unique_id, error=res.error)
> AttributeError: 'NoneType' object has no attribute 'unique_id'
> <Greenlet at 0xb566cdecL: handle_message(<Queue at 0xb566e78cL getters[1]>, '{"jsonrpc": "2.0", "params": ["insoftindianew"], )> failed with AttributeError
>

**Comment by pipermerriam** [comment]
This looks a lot like a bug in pyethapp.  Are you able to use something like `web3js` to call the same API endpoint and see if the error persists?

**Comment by pipermerriam** [comment]
@insoftayyappans can you run `pip freeze` and tell me what version of `gevent` you have installed?
