### ISSUE TITLE
Intermittent timeout problems

### ISSUE THREAD

**Issue by glowkeeper** [pipermerriam/web3.py#160]
* Version: latest from the main branch
* Python: 2.7.12
* OS: ubuntu 16.04

### What was wrong?

I have 3k+ database records to write to a smart contract. Unfortunately, after writing a few records, I'm getting intermittent timeout problems. Here's a traceback of one such occasion:

```
Traceback (most recent call last):
  File "dataReader.py", line 306, in <module>
    main()
  File "dataReader.py", line 303, in main
    blockchain_writer.writeRecords()
  File "dataReader.py", line 242, in writeRecords
    self.__setCulturalHeritageRecord(coId, record[self.cultural_heritage_keys[CulturalHeritageIndexList.AccessionNumber]])
  File "dataReader.py", line 186, in __setCulturalHeritageRecord
    self.contract.transact().createCulturalHeritageRecord(coId, accessionNumber)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/contract.py", line 815, in transact_with_contract_function
    txn_hash = contract.web3.eth.sendTransaction(transact_transaction)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/utils/string.py", line 86, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/eth.py", line 252, in sendTransaction
    transaction=formatted_transaction,
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/utils/transactions.py", line 53, in get_buffered_gas_estimate
    gas_estimate = web3.eth.estimateGas(gas_estimate_transaction)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/utils/functional.py", line 22, in inner
    value = fn(*args, **kwargs)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/eth.py", line 295, in estimateGas
    [formatted_transaction],
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/providers/manager.py", line 42, in request_blocking
    response_raw = self.provider.make_request(method, params)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/providers/rpc.py", line 49, in make_request
    **self.get_request_kwargs()
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/web3/utils/compat/compat_requests.py", line 21, in make_post_request
    response = session.post(endpoint_uri, data=data, *args, **kwargs)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/s/sh/sh601/.local/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=8545): Read timed out. (read timeout=10)
```
..._geth_ was busy mining a potential block at that point. Any ideas how  I might overcome that? I'd rather block and wait (or something) rather than just fail....

#### Cute Animal Picture

![This will grow up to be a vicious killer](http://4.bp.blogspot.com/_Q_4mbCuV7QE/SwNM5RDV5XI/AAAAAAAAG2Q/aTesAwZDN1I/s400/2exhausted_kitten.jpg)

**Comment by glowkeeper** [comment]
Actually, this currently seems to be working:

`self.provider = Web3(KeepAliveRPCProvider(host=host, port=port,_timeout=None_))`

Rather than:

`self.provider = Web3(KeepAliveRPCProvider(host=host, port=port))`

...okay, so it blocks for ages (until my slow machine actually gets 'round to mining the block), but it doesn't crash. Yay!

**Comment by pipermerriam** [comment]
You beat me to it.  Glad you got it figured out.  Let me know if you have continued troubles.

**Comment by glowkeeper** [comment]
Thanks pipermerriam! 

ps. I had a json export from a database to load into ethereum - it would have been an absolute pain via web3.js, but a breeze with python and web3.py - thanks for all your efforts :)
