### ISSUE TITLE
Updating web3 breaks things

### ISSUE THREAD

**Issue by shayanb** [pipermerriam/web3.py#183]
* Version: 3.8.1
* Python: 2.7
* OS: osx

### What was wrong?
I was trying to get web3 to transact with a Token contract I made, all the call() functions were working but I was getting an error on transact methods or just simply sending transactions.

```
    this_contract = web3rpc.eth.contract(json.loads(abi_json), address=contract_address)
    print transfer_tokens_to
    print web3rpc.eth.blockNumber
    print this_contract.call().name()
    print "from: %s " %web3rpc.eth.accounts[0]
    print "balance of: %s" %this_contract.call().balanceOf(web3rpc.eth.accounts[0])
    from_address_unlocked = unlock_geth_account(web3rpc.eth.accounts[0])
    print from_address_unlocked
    transfer_result = web3rpc.eth.sendTransaction({'from':web3rpc.eth.accounts[0], 'gas':30000000, 'value':111, 'to':contract_address}) #.transfer(transfer_tokens_to, 150)
```
Output before Web3 update, error on sending transactions :
```
0xc2285f89B5b228E9a51f2B80dd0712F0ac071C9e
1022057
Faast test token
from: 0xf9357f4fdef81103ed55296649a7cacf04e80ef3
balance of: 89000
unlocking 0xf9357f4fdef81103ed55296649a7cacf04e80ef3
True
Traceback (most recent call last):
  File "ethSender_testfile.py", line 67, in <module>
    send_token()
  File "ethSender_testfile.py", line 62, in send_token
    transfer_result = web3rpc.eth.sendTransaction({'gas':30000000, 'value':111, 'to':contract_address})#.transfer(transfer_tokens_to, 150)
  File "/usr/local/lib/python2.7/site-packages/web3/eth.py", line 223, in sendTransaction
    [formatted_transaction],
  File "/usr/local/lib/python2.7/site-packages/web3/providers/manager.py", line 25, in request_blocking
    raise ValueError(response["error"])
ValueError: {u'message': u'invalid argument 0: cannot unmarshal non-string as hex data', u'code': -32602}
```

So I decided to update web3 and all the dependencies in the hope that it might have been fixed. But now apparently the update has broken the way web3 reads the ABI.

Output after update:

```
0xc2285f89B5b228E9a51f2B80dd0712F0ac071C9e
1022196
Traceback (most recent call last):
  File "ethSender_testfile.py", line 64, in <module>
    send_token()
  File "ethSender_testfile.py", line 54, in send_token
    print this_contract.call().name()
  File "eth_tests/venv/lib/python2.7/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "eth_tests/venv/lib/python2.7/site-packages/web3/contract.py", line 759, in call_contract_function
    transaction=transaction,
  File "eth_tests/venv/lib/python2.7/site-packages/web3/utils/decorators.py", line 12, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "eth_tests/venv/lib/python2.7/site-packages/web3/contract.py", line 680, in _prepare_transaction
    fn_kwargs,
  File "eth_tests/venv/lib/python2.7/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "eth_tests/venv/lib/python2.7/site-packages/web3/contract.py", line 719, in _encode_transaction_data
    fn_name, args, kwargs,
  File "eth_tests/venv/lib/python2.7/site-packages/web3/contract.py", line 648, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "eth_tests/venv/lib/python2.7/site-packages/web3/contract.py", line 601, in _find_matching_fn_abi
    function_candidates = filter_by_type('function', cls.abi)
  File "eth_tests/venv/lib/python2.7/site-packages/web3/utils/abi.py", line 23, in filter_by_type
    return [abi for abi in contract_abi if abi['type'] == _type]
TypeError: 'NoneType' object is not iterable
```
Either the web3.py API has changed but the documentation is not updated or things are broken.

These are the variables if you want to reproduce the issue:

```
contract_address = "0xe72bbed5cf09686c62ed5be8f571a7670c11c468" #on testnet Ropsten
abi_json = '[{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"}],"name":"approve","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transferFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"decimals","outputs":[{"name":"","type":"uint8"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_value","type":"uint256"}],"name":"burn","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"standard","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_from","type":"address"},{"name":"_value","type":"uint256"}],"name":"burnFrom","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_value","type":"uint256"}],"name":"transfer","outputs":[],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_spender","type":"address"},{"name":"_value","type":"uint256"},{"name":"_extraData","type":"bytes"}],"name":"approveAndCall","outputs":[{"name":"success","type":"bool"}],"payable":false,"type":"function"},{"constant":true,"inputs":[{"name":"","type":"address"},{"name":"","type":"address"}],"name":"allowance","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[],"payable":false,"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Transfer","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":false,"name":"value","type":"uint256"}],"name":"Burn","type":"event"}]'
```

#### Cute Animal Picture

![Cute animal picture](http://s3.favim.com/orig/43/animal-crazy-cute-dog-funny-Favim.com-364925.jpg)

**Comment by shayanb** [comment]
this was fixed by using argument names for contract class.

```
    this_contract = web3rpc.eth.contract(abi = json.loads(abi_json), address=contract_address)
```

**Comment by frosty00** [comment]
I had the same issue. It seems it can also be reproduced by trying to set
`this_contract.abi = json.loads(abi_json)`
after the contract class had been initiated
