### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Haruka321** [pipermerriam/web3.py#192]
Version: newest
Python: 2.7 & 3.5
OS: linux

I get the error "TypeError: string indices must be integers" in line 12 "print(con.call().getBalance())"

```
from web3 import Web3, RPCProvider,KeepAliveRPCProvider, IPCProvider
import web3

web3 = Web3(IPCProvider())
print(web3.eth.accounts[0])
abi = 'abi'
fContract = web3.eth.contract(abi)
con=fContract("0xaddress")
print(con.call().getBalance())
```

Is there anything wrong with the code? There isn't that much documented so I can't tell it for sure

**Comment by pipermerriam** [comment]
Can you post the full stack trace for the error?

**Comment by Haruka321** [comment]
Thanks for the quick response
Thats the full error log
```
Traceback (most recent call last):
  File "/home/jesus/Desktop/web3python.py", line 19, in <module>
    print(fContract.call({'to':"0x7B80779C5DE173b1A30011aA290cdB62f5B8b1A9"}).isContractStarted())
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 757, in call_contract_function
    transaction=transaction,
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/decorators.py", line 14, in _wrapper
    return self.method(objtype, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 678, in _prepare_transaction
    fn_kwargs,
  File "/usr/local/lib/python3.5/dist-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 717, in _encode_transaction_data
    fn_name, args, kwargs,
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 646, in _get_function_info
    fn_abi = cls._find_matching_fn_abi(fn_name, args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/web3/contract.py", line 599, in _find_matching_fn_abi
    function_candidates = filter_by_type('function', cls.abi)
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/abi.py", line 23, in filter_by_type
    return [abi for abi in contract_abi if abi['type'] == _type]
  File "/usr/local/lib/python3.5/dist-packages/web3/utils/abi.py", line 23, in <listcomp>
    return [abi for abi in contract_abi if abi['type'] == _type]
TypeError: string indices must be integers
```

**Comment by pipermerriam** [comment]
Looks like you are not passing in a valid ABI (or that the ABI you are passing in is still a JSON string).  The `web3.eth.contract` API requires that the `abi` parameter be a dictionary (the result of parsing the JSON string).

I'm closing this under the assumption that this is the case.  Re-open if it is not.  I'm opening a new issue to add validation to the `abi` parameter to make it harder to make this error.
