### ISSUE TITLE
Getting past event logs throws "ValueError: Expected 0 log topics.  Got 1" after adding indexed parameters to event

### ISSUE THREAD

**Issue by jantristanmilan** [pipermerriam/web3.py#226]
* Version: 3.11.0
* Python: 3.6.2
* OS: osx
* Provider: testrpc

Solidity contracts compiled and deployed using Truffle. I just used the compiled JSON files in my Django App. I was able to retrieve the logs before using the same code. But I encountered this problem after adding an `indexed` modifier to one of the parameters of the event.

Signature of Event:
EventCreated(uint256 indexed var1, string var2)

### Code

```
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import division

import json
import os
import myapp.settings as settings

from web3 import Web3, KeepAliveRPCProvider
from django_rq import job
from myapp.models import CrowdsaleAddress


web3 = Web3(KeepAliveRPCProvider(host='localhost', port='8545'))

# Setting up of crowdsale contract
crowdsale_address = CrowdsaleAddress.objects.get().deployed_address
crowdsale_json_path = os.path.join(settings.BASE_DIR, 'static', 'contracts', 'CrowdsaleContract.json')
crowdsale_json_file = open(crowdsale_json_path)
crowdsale_json = json.load(crowdsale_json_file)
crowdsale_abi = crowdsale_json['abi']

crowdsale_contract = web3.eth.contract(address=crowdsale_address, abi=crowdsale_abi)

# Setting up of token contract
token_address = crowdsale_contract.call().token()

token_json_path = os.path.join(settings.BASE_DIR, 'static', 'contracts', 'MyToken.json')
token_json_file = open(token_json_path)
token_json = json.load(token_json_file)
token_abi = token_json['abi']

# Brute-force fix for web3.py bug, where constructor does not have a name key
token_abi = [abi for abi in token_abi if abi['type'] != 'constructor']

token_contract = web3.eth.contract(address=token_address, abi=token_abi)


token_contract.pastEvents('EventCreated',
              {"topics": {}, "fromBlock": 0, "toBlock": 'latest'}).get(only_changes=False)
```

### Stack Trace
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jantristanmilan/.virtualenvs/myapp-py3/lib/python3.6/site-packages/web3/utils/filters.py", line 178, in get
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/jantristanmilan/.virtualenvs/myapp-py3/lib/python3.6/site-packages/web3/utils/filters.py", line 178, in <listcomp>
    self.format_entry(log_entry) for log_entry in log_entries
  File "/Users/jantristanmilan/.virtualenvs/myapp-py3/lib/python3.6/site-packages/web3/utils/filters.py", line 184, in format_entry
    return self.log_entry_formatter(entry)
  File "/Users/jantristanmilan/.virtualenvs/myapp-py3/lib/python3.6/site-packages/eth_utils/string.py", line 85, in inner
    return force_obj_to_text(fn(*args, **kwargs))
  File "/Users/jantristanmilan/.virtualenvs/myapp-py3/lib/python3.6/site-packages/web3/utils/events.py", line 157, in get_event_data
    len(log_topics),
ValueError: Expected 0 log topics.  Got 1
```

### Attempted Fix
I tried doing the following but all it does is return an empty list of logs
```
token_contract.pastEvents('EventCreated', {"topics":[['0x7ce5c16b5d5fc1f0e2e65d7ee6ffb66bda38387e0ebf566bec33091d5eb1bd85']], "fromBlock": 0, "toBlock": 'latest'}).get(only_changes=False)

token_contract.pastEvents('EventCreated', {"topics":[[web3.sha("EventCreated(uint256,string)")]], "fromBlock": 0, "toBlock": 'latest'}).get(only_changes=False)

```

**Comment by pipermerriam** [comment]
Can you post the ABI for the `EventCreated` event?

**Comment by pipermerriam** [comment]
It looks like your ABI that you are using with your contract doesn't match the ABI of the event that is being logged.  The error you are receiving is web3 detecting that the log entry it is trying to decode does not match the format that it expects based on the event ABI and so it throws an error.

**Comment by jantristanmilan** [comment]
Oh I just used EventCreated as a template name for a code that reproduces the bug. The sha3 in the first example was an ABI for another function.

But I tried pasting all the sha3 in the JSON and it didnt work either

**Comment by jantristanmilan** [comment]
I tried reproducing the bug again in and it no longer appeared after I recompiled the contracts and repasted the JSON files. I must have committed a blunder in pasting the updated contracts before. Thanks for assisting me!
