### ISSUE TITLE
JSONBaseProvider.isConnected is broken

### ISSUE THREAD

**Issue by chenfengyuan** [pipermerriam/web3.py#299]
* Version: 3.13.5
* Python: 3.4.7
* OS: osx

### What was wrong?
JSONBaseProvide.isConnected is broken

call `web.isConnected()`

traceback:
```
Traceback (most recent call last):
  File "/Users/xxxxxxxxxxx/a.py", line 43, in __check_connected
    is_connected = self.web.isConnected()
  File "/Users/xxxxxxxxxx/lib/python3.4/site-packages/web3/main.py", line 184, in isConnected
    if provider.isConnected():
  File "/Users/xxxxxxxxxxxx/lib/python3.4/site-packages/web3/providers/base.py", line 58, in isConnected
    response = json.loads(force_text(response_raw))
  File "/Users/xxxxxxxxxxxx/lib/python3.4/site-packages/eth_utils/string.py", line 28, in force_text
    raise TypeError("Unsupported type: {0}".format(type(value)))
TypeError: Unsupported type: <class 'dict'>
```

### How can it be fixed?
fix in #298

**Comment by carver** [comment]
Thanks! This will go out with the next version release (next Monday, at the earliest).
