### ISSUE TITLE
FileNotFoundError on example code

### ISSUE THREAD

**Issue by msoedov** [pipermerriam/web3.py#373]
* Version: 
web3==3.16.2
* Python: 
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
* OS: osx

### What was wrong?

Please include any of the following that are applicable:

* The code which produced the error
```python
from web3 import Web3, HTTPProvider, IPCProvider

# Note that you should create only one RPCProvider per
# process, as it recycles underlying TCP/IP network connections between
# your process and Ethereum node
web3 = Web3(HTTPProvider('http://localhost:8545'))

# or for an IPC based connection
web3 = Web3(IPCProvider())

print(web3.eth.blockNumber)

```
* The full output of the error

```
Traceback (most recent call last):
  File "app.py", line 11, in <module>
    print(web3.eth.blockNumber)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/eth.py", line 92, in blockNumber
    return self.web3.manager.request_blocking("eth_blockNumber", [])
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/manager.py", line 93, in request_blocking
    response = self._make_request(method, params)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/manager.py", line 76, in _make_request
    return request_func(method, params)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/middleware/formatting.py", line 25, in middleware
    response = make_request(method, params)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/providers/ipc.py", line 84, in make_request
    with get_ipc_socket(self.ipc_path) as sock:
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/providers/ipc.py", line 32, in get_ipc_socket
    sock.connect(ipc_path)
FileNotFoundError: [Errno 2] No such file or directory

```
* What type of node you were connecting to.
testrpc

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by msoedov** [comment]
Prettified traceback 
```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
    new_transaction_filter = web3.eth.filter('pending')
                             └ <web3.main.Web3 object at 0x10333aac8>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/eth.py", line 275, in filter
    'eth_newPendingTransactionFilter', [],
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/manager.py", line 93, in request_blocking
    response = self._make_request(method, params)
               │                  │       └ []
               │                  └ 'eth_newPendingTransactionFilter'
               └ <web3.manager.RequestManager object at 0x10333aa90>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/manager.py", line 76, in _make_request
    return request_func(method, params)
           │            │       └ []
           │            └ 'eth_newPendingTransactionFilter'
           └ <function attrdict_middleware.<locals>.middleware at 0x10333c7b8>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/middleware/attrdict.py", line 20, in middleware
    response = make_request(method, params)
               │            │       └ []
               │            └ 'eth_newPendingTransactionFilter'
               └ <function construct_formatting_middleware.<locals>.formatter_middleware.<locals>.middleware at 0x10333c730>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/middleware/formatting.py", line 25, in middleware
    response = make_request(method, params)
               │            │       └ []
               │            └ 'eth_newPendingTransactionFilter'
               └ <bound method IPCProvider.make_request of <web3.providers.ipc.IPCProvider object at 0x10333aa58>>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/providers/ipc.py", line 84, in make_request
    with get_ipc_socket(self.ipc_path) as sock:
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
                └ <contextlib._GeneratorContextManager object at 0x10314ba90>
  File "/Users/msoedov/pyenvs/chain_notif/lib/python3.6/site-packages/web3/providers/ipc.py", line 32, in get_ipc_socket
    sock.connect(ipc_path)
    │            └ '/Users/msoedov/Library/Ethereum/geth.ipc'
    └ <socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by msoedov** [comment]
Found a typo :)

**Comment by OceansAndThunders** [comment]
Please include how were you able to solve the problem
