### ISSUE TITLE
AttributeError: module '_sha3' has no attribute 'sha3'

### ISSUE THREAD

**Issue by euri10** [pipermerriam/web3.py#56]
* Version: 1.6.0
* Python: 2.7/3.4/3.5
* OS: osx/linux/win

### What was wrong?
running tox pass the tests fine
but running them individually yields this error on some
I guess it's my local install since tox is fime, but couldnt find the root of it

```
➜  web3.py git:(master) ✗ sudo pip3 uninstall pysha3
Uninstalling pysha3-0.3:
  /usr/local/lib/python3.5/dist-packages/pysha3-0.3-py3.5-linux-x86_64.egg
```
pysha3 0.3 is install, seems to be the right version

```
─
➜  web3.py git:(master) ✗ py.test-3 tests/filtering/test_contract_on_event_filtering.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/lotsos/PycharmProjects/web3.py/tests/filtering/test_contract_on_event_filtering.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 283, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/lotsos/PycharmProjects/web3.py/tests/filtering')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 314, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/lotsos/PycharmProjects/web3.py/tests/filtering/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config.py", line 320, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/local/lib/python3.5/dist-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "/home/lotsos/PycharmProjects/web3.py/tests/filtering/conftest.py", line 6, in <module>
    assert sha3_256(b'').hexdigest() == 'c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
  File "/usr/local/lib/python3.5/dist-packages/sha3/__init__.py", line 97, in sha3_256
    return SHA3256(s)
  File "/usr/local/lib/python3.5/dist-packages/sha3/__init__.py", line 30, in __init__
    self._s = _sha3.sha3()
AttributeError: module '_sha3' has no attribute 'sha3'
ERROR: could not load /home/lotsos/PycharmProjects/web3.py/tests/filtering/conftest.py
```

#### Cute Animal Picture

> put a cute animal picture here.

**Comment by euri10** [comment]
fixed by uninstalling the wrong lib, gave me headaches 
```
➜  web3.py git:(master) ✗ sudo pip3 uninstall sha3
[sudo] password for lotsos:
Uninstalling sha3-0.2.1:
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/DESCRIPTION.rst
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/INSTALLER
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/METADATA
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/RECORD
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/WHEEL
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/metadata.json
  /usr/local/lib/python3.5/dist-packages/sha3-0.2.1.dist-info/top_level.txt
  /usr/local/lib/python3.5/dist-packages/sha3/__init__.py
  /usr/local/lib/python3.5/dist-packages/sha3/__pycache__/__init__.cpython-35.pyc
Proceed (y/n)? y
  Successfully uninstalled sha3-0.2.1
```
